__author__ = "Artem Kushch"
__copyright__ = "Copyright 2022, ISGNeuro"
__credits__ = []
__license__ = ""
__version__ = "0.0.1"
__api_version__ = "1"
__maintainer__ = "Artem Kushch"
__email__ = "akushch@isgneuro.com"
__status__ = "Develop"
